version: "3.8"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - order-service

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - database

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: microservices
      POSTGRES_USER: micro_user
      POSTGRES_PASSWORD: micro_pass
    ports:
      - "5432:5432"